In [39]:
import pandas as pd
import os
import json

In [26]:
import os
os.chdir('C:/ML/Network_Security/Network_Data')

In [27]:
file_path = os.path.join(os.getcwd(),'phisingData.csv')

In [28]:
data = pd.read_csv(file_path)

In [32]:
data.duplicated().sum()

np.int64(5206)

In [33]:
data.head()

,having_IP_Address,URL_Length,Shortining_Service,having_At_Symbol,double_slash_redirecting,Prefix_Suffix,having_Sub_Domain,SSLfinal_State,Domain_registeration_length,Favicon,...,popUpWidnow,Iframe,age_of_domain,DNSRecord,web_traffic,Page_Rank,Google_Index,Links_pointing_to_page,Statistical_report,Result
0,-1,1,1,1,-1,-1,-1,-1,-1,1,...,1,1,-1,-1,-1,-1,1,1,-1,-1
1,1,1,1,1,1,-1,0,1,-1,1,...,1,1,-1,-1,0,-1,1,1,1,-1
2,1,0,1,1,1,-1,-1,-1,-1,1,...,1,1,1,-1,1,-1,1,0,-1,-1
3,1,0,1,1,1,-1,-1,-1,1,1,...,1,1,-1,-1,1,-1,1,-1,1,-1
4,1,0,-1,1,1,-1,1,1,-1,1,...,-1,1,-1,-1,0,-1,1,1,1,1

In [34]:
data.reset_index(drop=True,inplace=True)

In [35]:
data.head(20)

,having_IP_Address,URL_Length,Shortining_Service,having_At_Symbol,double_slash_redirecting,Prefix_Suffix,having_Sub_Domain,SSLfinal_State,Domain_registeration_length,Favicon,...,popUpWidnow,Iframe,age_of_domain,DNSRecord,web_traffic,Page_Rank,Google_Index,Links_pointing_to_page,Statistical_report,Result
0,-1,1,1,1,-1,-1,-1,-1,-1,1,...,1,1,-1,-1,-1,-1,1,1,-1,-1
1,1,1,1,1,1,-1,0,1,-1,1,...,1,1,-1,-1,0,-1,1,1,1,-1
2,1,0,1,1,1,-1,-1,-1,-1,1,...,1,1,1,-1,1,-1,1,0,-1,-1
3,1,0,1,1,1,-1,-1,-1,1,1,...,1,1,-1,-1,1,-1,1,-1,1,-1
4,1,0,-1,1,1,-1,1,1,-1,1,...,-1,1,-1,-1,0,-1,1,1,1,1
5,-1,0,-1,1,-1,-1,1,1,-1,1,...,1,1,1,1,1,-1,1,-1,-1,1
6,1,0,-1,1,1,-1,-1,-1,1,1,...,1,1,1,-1,-1,-1,1,0,-1,-1
7,1,0,1,1,1,-1,-1,-1,1,1,...,1,1,-1,-1,0,-1,1,0,1,-1
8,1,0,-1,1,1,-1,1,1,-1,1,...,1,1,1,-1,1,1,1,0,1,1
9,1,1,-1,1,1,-1,-1,1,-1,1,...,1,1,1,-1,0,-1,1,0,1,-1
10,1,1,1,1,1,-1,0,1,1,1,...,1,1,-1,1,1,1,1,-1,-1,1
11,1,1,-1,1,1,-1,1,-1,-1,1,...,1,1,-1,-1,-1,-1,1,0,-1,-1
12,-1,1,-1,1,-1,-1,0,0,1,1,...,-1,1,1,-1,-1,-1,1,0,1,-1
13,1,1,-1,1,1,-1,0,-1,1,1,...,1,1,-1,-1,0,-1,1,1,1,-1
14,1,1,-1,1,1,1,-1,1,-1,1,...,1,1,1,-1,1,-1,1,-1,1,1
15,1,-1,-1,-1,1,-1,0,0,1,1,...,1,1,1,-1,-1,-1,1,0,1,-1
16,1,-1,-1,1,1,-1,1,1,-1,1,...,1,1,1,-1,0,-1,1,1,-1,-1
17,1,-1,1,1,1,-1,-1,0,1,1,...,1,1,-1,1,1,-1,1,1,-1,-1
18,1,1,1,1,1,-1,-1,1,1,1,...,1,1,1,-1,-1,1,1,-1,-1,1
19,1,1,1,1,1,-1,-1,1,-1,1,...,-1,-1,1,-1,0,-1,1,0,-1,1

In [43]:
print(list((json.loads(data.T.to_json()).values())))

[{'having_IP_Address': -1, 'URL_Length': 1, 'Shortining_Service': 1, 'having_At_Symbol': 1, 'double_slash_redirecting': -1, 'Prefix_Suffix': -1, 'having_Sub_Domain': -1, 'SSLfinal_State': -1, 'Domain_registeration_length': -1, 'Favicon': 1, 'port': 1, 'HTTPS_token': -1, 'Request_URL': 1, 'URL_of_Anchor': -1, 'Links_in_tags': 1, 'SFH': -1, 'Submitting_to_email': -1, 'Abnormal_URL': -1, 'Redirect': 0, 'on_mouseover': 1, 'RightClick': 1, 'popUpWidnow': 1, 'Iframe': 1, 'age_of_domain': -1, 'DNSRecord': -1, 'web_traffic': -1, 'Page_Rank': -1, 'Google_Index': 1, 'Links_pointing_to_page': 1, 'Statistical_report': -1, 'Result': -1}, {'having_IP_Address': 1, 'URL_Length': 1, 'Shortining_Service': 1, 'having_At_Symbol': 1, 'double_slash_redirecting': 1, 'Prefix_Suffix': -1, 'having_Sub_Domain': 0, 'SSLfinal_State': 1, 'Domain_registeration_length': -1, 'Favicon': 1, 'port': 1, 'HTTPS_token': -1, 'Request_URL': 1, 'URL_of_Anchor': 0, 'Links_in_tags': -1, 'SFH': -1, 'Submitting_to_email': 1, 'Abnormal_URL': 1, 'Redirect': 0, 'on_mouseover': 1, 'RightClick': 1, 'popUpWidnow': 1, 'Iframe': 1, 'age_of_domain': -1, 'DNSRecord': -1, 'web_traffic': 0, 'Page_Rank': -1, 'Google_Index': 1, 'Links_pointing_to_page': 1, 'Statistical_report': 1, 'Result': -1}, {'having_IP_Address': 1, 'URL_Length': 0, 'Shortining_Service': 1, 'having_At_Symbol': 1, 'double_slash_redirecting': 1, 'Prefix_Suffix': -1, 'having_Sub_Domain': -1, 'SSLfinal_State': -1, 'Domain_registeration_length': -1, 'Favicon': 1, 'port': 1, 'HTTPS_token': -1, 'Request_URL': 1, 'URL_of_Anchor': 0, 'Links_in_tags': -1, 'SFH': -1, 'Submitting_to_email': -1, 'Abnormal_URL': -1, 'Redirect': 0, 'on_mouseover': 1, 'RightClick': 1, 'popUpWidnow': 1, 'Iframe': 1, 'age_of_domain': 1, 'DNSRecord': -1, 'web_traffic': 1, 'Page_Rank': -1, 'Google_Index': 1, 'Links_pointing_to_page': 0, 'Statistical_report': -1, 'Result': -1}, {'having_IP_Address': 1, 'URL_Length': 0, 'Shortining_Service': 1, 'having_At_Symbol': 1, 'double_slash_redirecting': 1, 'Prefix_Suffix': -1, 'having_Sub_Domain': -1, 'SSLfinal_State': -1, 'Domain_registeration_length': 1, 'Favicon': 1, 'port': 1, 'HTTPS_token': -1, 'Request_URL': -1, 'URL_of_Anchor': 0, 'Links_in_tags': 0, 'SFH': -1, 'Submitting_to_email': 1, 'Abnormal_URL': 1, 'Redirect': 0, 'on_mouseover': 1, 'RightClick': 1, 'popUpWidnow': 1, 'Iframe': 1, 'age_of_domain': -1, 'DNSRecord': -1, 'web_traffic': 1, 'Page_Rank': -1, 'Google_Index': 1, 'Links_pointing_to_page': -1, 'Statistical_report': 1, 'Result': -1}, {'having_IP_Address': 1, 'URL_Length': 0, 'Shortining_Service': -1, 'having_At_Symbol': 1, 'double_slash_redirecting': 1, 'Prefix_Suffix': -1, 'having_Sub_Domain': 1, 'SSLfinal_State': 1, 'Domain_registeration_length': -1, 'Favicon': 1, 'port': 1, 'HTTPS_token': 1, 'Request_URL': 1, 'URL_of_Anchor': 0, 'Links_in_tags': 0, 'SFH': -1, 'Submitting_to_email': 1, 'Abnormal_URL': 1, 'Redirect': 0, 'on_mouseover': -1, 'RightClick': 1, 'popUpWidnow': -1, 'Iframe': 1, 'age_of_domain': -1, 'DNSRecord': -1, 'web_traffic': 0, 'Page_Rank': -1, 'Google_Index': 1, 'Links_pointing_to_page': 1, 'Statistical_report': 1, 'Result': 1}, {'having_IP_Address': -1, 'URL_Length': 0, 'Shortining_Service': -1, 'having_At_Symbol': 1, 'double_slash_redirecting': -1, 'Prefix_Suffix': -1, 'having_Sub_Domain': 1, 'SSLfinal_State': 1, 'Domain_registeration_length': -1, 'Favicon': 1, 'port': 1, 'HTTPS_token': -1, 'Request_URL': 1, 'URL_of_Anchor': 0, 'Links_in_tags': 0, 'SFH': -1, 'Submitting_to_email': -1, 'Abnormal_URL': -1, 'Redirect': 0, 'on_mouseover': 1, 'RightClick': 1, 'popUpWidnow': 1, 'Iframe': 1, 'age_of_domain': 1, 'DNSRecord': 1, 'web_traffic': 1, 'Page_Rank': -1, 'Google_Index': 1, 'Links_pointing_to_page': -1, 'Statistical_report': -1, 'Result': 1}, {'having_IP_Address': 1, 'URL_Length': 0, 'Shortining_Service': -1, 'having_At_Symbol': 1, 'double_slash_redirecting': 1, 'Prefix_Suffix': -1, 'having_Sub_Domain': -1, 'SSLfinal_State': -1, 'Domain_registeration_length': 1, 'Favicon': 1, 'port': 1, 'HTTPS_token': 1, 'Request_URL': -1, 'URL_of_Anchor': -1, 'Links_in_tags': 0, 'SFH': -1, 'Submitting_to_email': -1, 'Abnormal_URL': -1, 'Redirect': 0, 'on_mouseover': 1, 'RightClick': 1, 'popUpWidnow': 1, 'Iframe': 1, 'age_of_domain': 1, 'DNSRecord': -1, 'web_traffic': -1, 'Page_Rank': -1, 'Google_Index': 1, 'Links_pointing_to_page': 0, 'Statistical_report': -1, 'Result': -1}, {'having_IP_Address': 1, 'URL_Length': 0, 'Shortining_Service': 1, 'having_At_Symbol': 1, 'double_slash_redirecting': 1, 'Prefix_Suffix': -1, 'having_Sub_Domain': -1, 'SSLfinal_State': -1, 'Domain_registeration_length': 1, 'Favicon': 1, 'port': 1, 'HTTPS_token': -1, 'Request_URL': -1, 'URL_of_Anchor': 0, 'Links_in_tags': -1, 'SFH': -1, 'Submitting_to_email': 1, 'Abnormal_URL': 1, 'Redirect': 0, 'on_mouseover': 1, 'RightClick': 1, 'popUpWidnow': 1, 'Iframe': 1, 'age_of_domain': -1, 'DNSRecord': -1, 'web_traffic': 0, 'Page_Rank': -1, 'Google_Index': 1, 'Links_pointing_to_page': 0, 'Statistical_report': 1, 'Result': -1}, {'having_IP_Address': 1, 'URL_Length': 0, 'Shortining_Service': -1, 'having_At_Symbol': 1, 'double_slash_redirecting': 1, 'Prefix_Suffix': -1, 'having_Sub_Domain': 1, 'SSLfinal_State': 1, 'Domain_registeration_length': -1, 'Favicon': 1, 'port': 1, 'HTTPS_token': -1, 'Request_URL': 1, 'URL_of_Anchor': 0, 'Links_in_tags': 1, 'SFH': -1, 'Submitting_to_email': 1, 'Abnormal_URL': 1, 'Redirect': 0, 'on_mouseover': 1, 'RightClick': 1, 'popUpWidnow': 1, 'Iframe': 1, 'age_of_domain': 1, 'DNSRecord': -1, 'web_traffic': 1, 'Page_Rank': 1, 'Google_Index': 1, 'Links_pointing_to_page': 0, 'Statistical_report': 1, 'Result': 1}, {'having_IP_Address': 1, 'URL_Length': 1, 'Shortining_Service': -1, 'having_At_Symbol': 1, 'double_slash_redirecting': 1, 'Prefix_Suffix': -1, 'having_Sub_Domain': -1, 'SSLfinal_State': 1, 'Domain_registeration_length': -1, 'Favicon': 1, 'port': 1, 'HTTPS_token': 1, 'Request_URL': 1, 'URL_of_Anchor': 0, 'Links_in_tags': 1, 'SFH': -1, 'Submitting_to_email': 1, 'Abnormal_URL': 1, 'Redirect': 0, 'on_mouseover': 1, 'RightClick': 1, 'popUpWidnow': 1, 'Iframe': 1, 'age_of_domain': 1, 'DNSRecord': -1, 'web_traffic': 0, 'Page_Rank': -1, 'Google_Index': 1, 'Links_pointing_to_page': 0, 'Statistical_report': 1, 'Result': -1}, {'having_IP_Address': 1, 'URL_Length': 1, 'Shortining_Service': 1, 'having_At_Symbol': 1, 'double_slash_redirecting': 1, 'Prefix_Suffix': -1, 'having_Sub_Domain': 0, 'SSLfinal_State': 1, 'Domain_registeration_length': 1, 'Favicon': 1, 'port': 1, 'HTTPS_token': 1, 'Request_URL': -1, 'URL_of_Anchor': 0, 'Links_in_tags': 0, 'SFH': -1, 'Submitting_to_email': -1, 'Abnormal_URL': -1, 'Redirect': 0, 'on_mouseover': 1, 'RightClick': 1, 'popUpWidnow': 1, 'Iframe': 1, 'age_of_domain': -1, 'DNSRecord': 1, 'web_traffic': 1, 'Page_Rank': 1, 'Google_Index': 1, 'Links_pointing_to_page': -1, 'Statistical_report': -1, 'Result': 1}, {'having_IP_Address': 1, 'URL_Length': 1, 'Shortining_Service': -1, 'having_At_Symbol': 1, 'double_slash_redirecting': 1, 'Prefix_Suffix': -1, 'having_Sub_Domain': 1, 'SSLfinal_State': -1, 'Domain_registeration_length': -1, 'Favicon': 1, 'port': 1, 'HTTPS_token': 1, 'Request_URL': 1, 'URL_of_Anchor': -1, 'Links_in_tags': -1, 'SFH': -1, 'Submitting_to_email': -1, 'Abnormal_URL': -1, 'Redirect': 0, 'on_mouseover': 1, 'RightClick': 1, 'popUpWidnow': 1, 'Iframe': 1, 'age_of_domain': -1, 'DNSRecord': -1, 'web_traffic': -1, 'Page_Rank': -1, 'Google_Index': 1, 'Links_pointing_to_page': 0, 'Statistical_report': -1, 'Result': -1}, {'having_IP_Address': -1, 'URL_Length': 1, 'Shortining_Service': -1, 'having_At_Symbol': 1, 'double_slash_redirecting': -1, 'Prefix_Suffix': -1, 'having_Sub_Domain': 0, 'SSLfinal_State': 0, 'Domain_registeration_length': 1, 'Favicon': 1, 'port': 1, 'HTTPS_token': -1, 'Request_URL': -1, 'URL_of_Anchor': -1, 'Links_in_tags': 1, 'SFH': -1, 'Submitting_to_email': 1, 'Abnormal_URL': 1, 'Redirect': 0, 'on_mouseover': -1, 'RightClick': 1, 'popUpWidnow': -1, 'Iframe': 1, 'age_of_domain': 1, 'DNSRecord': -1, 'web_traffic': -1, 'Page_Rank': -1, 'Google_Index': 1, 'Links_pointing_to_page': 0, 'Statistical_report': 1, 'Result': -1}, {'having_IP_Address': 1, 'URL_Length': 1, 'Shortining_Service': -1, 'having_At_Symbol': 1, 'double_slash_redirecting': 1, 'Prefix_Suffix': -1, 'having_Sub_Domain': 0, 'SSLfinal_State': -1, 'Domain_registeration_length': 1, 'Favicon': 1, 'port': 1, 'HTTPS_token': 1, 'Request_URL': -1, 'URL_of_Anchor': -1, 'Links_in_tags': -1, 'SFH': -1, 'Submitting_to_email': 1, 'Abnormal_URL': 1, 'Redirect': 0, 'on_mouseover': 1, 'RightClick': 1, 'popUpWidnow': 1, 'Iframe': 1, 'age_of_domain': -1, 'DNSRecord': -1, 'web_traffic': 0, 'Page_Rank': -1, 'Google_Index': 1, 'Links_pointing_to_page': 1, 'Statistical_report': 1, 'Result': -1}, {'having_IP_Address': 1, 'URL_Length': 1, 'Shortining_Service': -1, 'having_At_Symbol': 1, 'double_slash_redirecting': 1, 'Prefix_Suffix': 1, 'having_Sub_Domain': -1, 'SSLfinal_State': 1, 'Domain_registeration_length': -1, 'Favicon': 1, 'port': 1, 'HTTPS_token': -1, 'Request_URL': 1, 'URL_of_Anchor': 0, 'Links_in_tags': 1, 'SFH': 1, 'Submitting_to_email': 1, 'Abnormal_URL': 1, 'Redirect': 0, 'on_mouseover': 1, 'RightClick': 1, 'popUpWidnow': 1, 'Iframe': 1, 'age_of_domain': 1, 'DNSRecord': -1, 'web_traffic': 1, 'Page_Rank': -1, 'Google_Index': 1, 'Links_pointing_to_page': -1, 'Statistical_report': 1, 'Result': 1}, {'having_IP_Address': 1, 'URL_Length': -1, 'Shortining_Service': -1, 'having_At_Symbol': -1, 'double_slash_redirecting': 1, 'Prefix_Suffix': -1, 'having_Sub_Domain': 0, 'SSLfinal_State': 0, 'Domain_registeration_length': 1, 'Favicon': 1, 'port': 1, 'HTTPS_token': 1, 'Request_URL': -1, 'URL_of_Anchor': -1, 'Links_in_tags': 0, 'SFH': -1, 'Submitting_to_email': 1, 'Abnormal_URL': 1, 'Redirect': 0, 'on_mouseover': 1, 'RightClick': 1, 'popUpWidnow': 1, 'Iframe': 1, 'age_of_domain': 1, 'DNSRecord': -1, 'web_traffic': -1, 'Page_Rank': -1, 'Google_Index': 1, 'Links_pointing_to_page': 0, 'Statistical_report': 1, 'Result': -1}, {'having_IP_Address': 1, 'URL_Length': -1, 'Shortining_Service': -1, 'having_At_Symbol': 1, 'double_slash_redirecting': 1, 'Prefix_Suffix': -1, 'having_Sub_Domain': 1, 'SSLfinal_State': 1, 'Domain_registeration_length': -1, 'Favicon': 1, 'port': 1, 'HTTPS_token': -1, 'Request_URL': 1, 'URL_of_Anchor': 0, 'Links_in_tags': -1, 'SFH': -1, 'Submitting_to_email': -1, 'Abnormal_URL': -1, 'Redirect': 0, 'on_mouseover': 1, 'RightClick': 1, 'popUpWidnow': 1, 'Iframe': 1, 'age_of_domain': 1, 'DNSRecord': -1, 'web_traffic': 0, 'Page_Rank': -1, 'Google_Index': 1, 'Links_pointing_to_page': 1, 'Statistical_report': -1, 'Result': -1}, {'having_IP_Address': 1, 'URL_Length': -1, 'Shortining_Service': 1, 'having_At_Symbol': 1, 'double_slash_redirecting': 1, 'Prefix_Suffix': -1, 'having_Sub_Domain': -1, 'SSLfinal_State': 0, 'Domain_registeration_length': 1, 'Favicon': 1, 'port': -1, 'HTTPS_token': 1, 'Request_URL': 1, 'URL_of_Anchor': 0, 'Links_in_tags': -1, 'SFH': -1, 'Submitting_to_email': -1, 'Abnormal_URL': -1, 'Redirect': 0, 'on_mouseover': 1, 'RightClick': 1, 'popUpWidnow': 1, 'Iframe': 1, 'age_of_domain': -1, 'DNSRecord': 1, 'web_traffic': 1, 'Page_Rank': -1, 'Google_Index': 1, 'Links_pointing_to_page': 1, 'Statistical_report': -1, 'Result': -1}, {'having_IP_Address': 1, 'URL_Length': 1, 'Shortining_Service': 1, 'having_At_Symbol': 1, 'double_slash_redirecting': 1, 'Prefix_Suffix': -1, 'having_Sub_Domain': -1, 'SSLfinal_State': 1, 'Domain_registeration_length': 1, 'Favicon': 1, 'port': 1, 'HTTPS_token': -1, 'Request_URL': -1, 'URL_of_Anchor': 0, 'Links_in_tags': -1, 'SFH': -1, 'Submitting_to_email': -1, 'Abnormal_URL': -1, 'Redirect': 0, 'on_mouseover': 1, 'RightClick': 1, 'popUpWidnow': 1, 'Iframe': 1, 'age_of_domain': 1, 'DNSRecord': -1, 'web_traffic': -1, 'Page_Rank': 1, 'Google_Index': 1, 'Links_pointing_to_page': -1, 'Statistical_report': -1, 'Result': 1}, {'having_IP_Address': 1, 'URL_Length': 1, 'Shortining_Service': 1, 'having_At_Symbol': 1, 'double_slash_redirecting': 1, 'Prefix_Suffix': -1, 'having_Sub_Domain': -1, 'SSLfinal_State': 1, 'Domain_registeration_length': -1, 'Favicon': 1, 'port': 1, 'HTTPS_token': 1, 'Request_URL': 1, 'URL_of_Anchor': 0, 'Links_in_tags': 0, 'SFH': -1, 'Submitting_to_email': -1, 'Abnormal_URL': -1, 'Redirect': 0, 'on_mouseover': -1, 'RightClick': -1, 'popUpWidnow': -1, 'Iframe': -1, 'age_of_domain': 1, 'DNSRecord': -1, 'web_traffic': 0, 'Page_Rank': -1, 'Google_Index': 1, 'Links_pointing_to_page': 0, 'Statistical_report': -1, 'Result': 1}, {'having_IP_Address': 1, 'URL_Length': 0, 'Shortining_Service': -1, 'having_At_Symbol': 1, 'double_slash_redirecting': 1, 'Prefix_Suffix': -1, 'having_Sub_Domain': 0, 'SSLfinal_State': 1, 'Domain_registeration_length': -1, 'Favicon': 1, 'port': 1, 'HTTPS_token': 1, 'Request_URL': 1, 'URL_of_Anchor': 0, 'Links_in_tags': 0, 'SFH': -1, 'Submitting_to_email': -1, 'Abnormal_URL': -1, 'Redirect': 0, 'on_mouseover': -1, 'RightClick': 1, 'popUpWidnow': -1, 'Iframe': 1, 'age_of_domain': -1, 'DNSRecord': 1, 'web_traffic': 1, 'Page_Rank': -1, 'Google_Index': 1, 'Links_pointing_to_page': -1, 'Statistical_report': -1, 'Result': 1}, {'having_IP_Address': 1, 'URL_Length': 0, 'Shortining_Service': 1, 'having_At_Symbol': 1, 'double_slash_redirecting': 1, 'Prefix_Suffix': -1, 'having_Sub_Domain': 0, 'SSLfinal_State': 1, 'Domain_registeration_length': 1, 'Favicon': 1, 'port': 1, 'HTTPS_token': -1, 'Request_URL': -1, 'URL_of_Anchor': 0, 'Links_in_tags': -1, 'SFH': -1, 'Submitting_to_email': -1, 'Abnormal_URL': -1, 'Redirect': 0, 'on_mouseover': 1, 'RightClick': 1, 'popUpWidnow': 1, 'Iframe': 1, 'age_of_domain': -1, 'DNSRecord': 1, 'web_traffic': -1, 'Page_Rank': -1, 'Google_Index': 1, 'Links_pointing_to_page': 0, 'Statistical_report': -1, 'Result': 1}, {'having_IP_Address': 1, 'URL_Length': 1, 'Shortining_Service': 1, 'having_At_Symbol': 1, 'double_slash_redirecting': 1, 'Prefix_Suffix': -1, 'having_Sub_Domain': -1, 'SSLfinal_State': -1, 'Domain_registeration_length': -1, 'Favicon': 1, 'port': 1, 'HTTPS_token': -1, 'Request_URL': 1, 'URL_of_Anchor': 0, 'Links_in_tags': 0, 'SFH': -1, 'Submitting_to_email': 1, 'Abnormal_URL': 1, 'Redirect': 0, 'on_mouseover': 1, 'RightClick': 1, 'popUpWidnow': 1, 'Iframe': 1, 'age_of_domain': 1, 'DNSRecord': 1, 'web_traffic': 0, 'Page_Rank': -1, 'Google_Index': 1, 'Links_pointing_to_page': -1, 'Statistical_report': 1, 'Result': 1}, {'having_IP_Address': 1, 'URL_Length': 1, 'Shortining_Service': 1, 'having_At_Symbol': 1, 'double_slash_redirecting': 1, 'Prefix_Suffix': -1, 'having_Sub_Domain': 1, 'SSLfinal_State': 0, 'Domain_registeration_length': -1, 'Favicon': 1, 'port': 1, 'HTTPS_token': 1, 'Request_URL': 1, 'URL_of_Anchor': 0, 'Links_in_tags': 0, 'SFH': -1, 'Submitting_to_email': 1, 'Abnormal_URL': 1, 'Redirect': 0, 'on_mouseover': 1, 'RightClick': 1, 'popUpWidnow': 1, 'Iframe': 1, 'age_of_domain': 1, 'DNSRecord': 1, 'web_traffic': 1, 'Page_Rank': -1, 'Google_Index': 1, 'Links_pointing_to_page': -1, 'Statistical_report': 1, 'Result': 1}, {'having_IP_Address': 1, 'URL_Length': -1, 'Shortining_Service': -1, 'having_At_Symbol': -1, 'double_slash_redirecting': 1, 'Prefix_Suffix': -1, 'having_Sub_Domain': 1, 'SSLfinal_State': 1, 'Domain_registeration_length': -1, 'Favicon': 1, 'port': 1, 'HTTPS_token': -1, 'Request_URL': -1, 'URL_of_Anchor': 0, 'Links_in_tags': 0, 'SFH': -1, 'Submitting_to_email': 1, 'Abnormal_URL': 1, 'Redirect': 0, 'on_mouseover': 1, 'RightClick': 1, 'popUpWidnow': 1, 'Iframe': 1, 'age_of_domain': 1, 'DNSRecord': 1, 'web_traffic': -1, 'Page_Rank': -1, 'Google_Index': 1, 'Links_pointing_to_page': 0, 'Statistical_report': 1, 'Result': 1}, {'having_IP_Address': 1, 'URL_Length': -1, 'Shortining_Service': 1, 'having_At_Symbol': 1, 'double_slash_redirecting': 1, 'Prefix_Suffix': -1, 'having_Sub_Domain': 0, 'SSLfinal_State': 1, 'Domain_registeration_length': -1, 'Favicon': 1, 'port': 1, 'HTTPS_token': 1, 'Request_URL': 1, 'URL_of_Anchor': 1, 'Links_in_tags': 0, 'SFH': -1, 'Submitting_to_email': 1, 'Abnormal_URL': 1, 'Redirect': 0, 'on_mouseover': 1, 'RightClick': 1, 'popUpWidnow': 1, 'Iframe': 1, 'age_of_domain': -1, 'DNSRecord': 1, 'web_traffic': 1, 'Page_Rank': -1, 'Google_Index': 1, 'Links_pointing_to_page': 0, 'Statistical_report': 1, 'Result': 1}, {'having_IP_Address': 1, 'URL_Length': -1, 'Shortining_Service': 1, 'having_At_Symbol': 1, 'double_slash_redirecting': 1, 'Prefix_Suffix': -1, 'having_Sub_Domain': 0, 'SSLfinal_State': -1, 'Domain_registeration_length': 1, 'Favicon': 1, 'port': 1, 'HTTPS_token': -1, 'Request_URL': -1, 'URL_of_Anchor': -1, 'Links_in_tags': -1, 'SFH': -1, 'Submitting_to_email': -1, 'Abnormal_URL': -1, 'Redirect': 0, 'on_mouseover': 1, 'RightClick': 1, 'popUpWidnow': 1, 'Iframe': 1, 'age_of_domain': 1, 'DNSRecord': 1, 'web_traffic': 0, 'Page_Rank': -1, 'Google_Index': 1, 'Links_pointing_to_page': -1, 'Statistical_report': -1, 'Result': -1}, {'having_IP_Address': 1, 'URL_Length': -1, 'Shortining_Service': -1, 'having_At_Symbol': 1, 'double_slash_redirecting': 1, 'Prefix_Suffix': 1, 'having_Sub_Domain': -1, 'SSLfinal_State': 1, 'Domain_registeration_length': 1, 'Favicon': 1, 'port': 1, 'HTTPS_token': 1, 'Request_URL': -1, 'URL_of_Anchor': 1, 'Links_in_tags': 0, 'SFH': -1, 'Submitting_to_email': -1, 'Abnormal_URL': -1, 'Redirect': 0, 'on_mouseover': 1, 'RightClick': 1, 'popUpWidnow': 1, 'Iframe': 1, 'age_of_domain': 1, 'DNSRecord': -1, 'web_traffic': 0, 'Page_Rank': -1, 'Google_Index': 1, 'Links_pointing_to_page': 0, 'Statistical_report': -1, 'Result': 1}, {'having_IP_Address': 1, 'URL_Length': -1, 'Shortining_Service': -1, 'having_At_Symbol': 1, 'double_slash_redirecting': -1, 'Prefix_Suffix': 1, 'having_Sub_Domain': -1, 'SSLfinal_State': 1, 'Domain_registeration_length': -1, 'Favicon': 1, 'port': 1, 'HTTPS_token': 1, 'Request_URL': 1, 'URL_of_Anchor': 1, 'Links_in_tags': 0, 'SFH': -1, 'Submitting_to_email': 1, 'Abnormal_URL': 1, 'Redirect': 1, 'on_mouseover': 1, 'RightClick': 1, 'popUpWidnow': 1, 'Iframe': 1, 'age_of_domain': -1, 'DNSRecord': -1, 'web_traffic': 1, 'Page_Rank': -1, 'Google_Index': 1, 'Links_pointing_to_page': -1, 'Statistical_report': 1, 'Result': 1}, {'having_IP_Address': 1, 'URL_Length': -1, 'Shortining_Service': 1, 'having_At_Symbol': 1, 'double_slash_redirecting': 1, 'Prefix_Suffix': -1, 'having_Sub_Domain': -1, 'SSLfinal_State': 1, 'Domain_registeration_length': -1, 'Favicon': 1, 'port': 1, 'HTTPS_token': 1, 'Request_URL': 1, 'URL_of_Anchor': 1, 'Links_in_tags': 0, 'SFH': -1, 'Submitting_to_email': 1, 'Abnormal_URL': 1, 'Redirect': 0, 'on_mouseover': 1, 'RightClick': 1, 'popUpWidnow': 1, 'Iframe': 1, 'age_of_domain': -1, 'DNSRecord': 1, 'web_traffic': 1, 'Page_Rank': 1, 'Google_Index': 1, 'Links_pointing_to_page': 0, 'Statistical_report': 1, 'Result': 1}, {'having_IP_Address': 1, 'URL_Length': -1, 'Shortining_Service': 1, 'having_At_Symbol': 1, 'double_slash_redirecting': 1, 'Prefix_Suffix': -1, 'having_Sub_Domain': -1, 'SSLfinal_State': 1, 'Domain_registeration_length': -1, 'Favicon': 1, 'port': 1, 'HTTPS_token': -1, 'Request_URL': 1, 'URL_of_Anchor': 0, 'Links_in_tags': 1, 'SFH': -1, 'Submitting_to_email': 1, 'Abnormal_URL': 1, 'Redirect': 0, 'on_mouseover': 1, 'RightClick': 1, 'popUpWidnow': 1, 'Iframe': 1, 'age_of_domain': -1, 'DNSRecord': -1, 'web_traffic': -1, 'Page_Rank': -1, 'Google_Index': 1, 'Links_pointing_to_page': 0, 'Statistical_report': 1, 'Result': 1}, {'having_IP_Address': 1, 'URL_Length': -1, 'Shortining_Service': 1, 'having_At_Symbol': 1, 'double_slash_redirecting': 1, 'Prefix_Suffix': -1, 'having_Sub_Domain': -1, 'SSLfinal_State': 1, 'Domain_registeration_length': -1, 'Favicon': -1, 'port': 1, 'HTTPS_token': -1, 'Request_URL': 1, 'URL_of_Anchor': 0, 'Links_in_tags': -1, 'SFH': -1, 'Submitting_to_email': -1, 'Abnormal_URL': -1, 'Redirect': 0, 'on_mouseover': -1, 'RightClick': 1, 'popUpWidnow': -1, 'Iframe': -1, 'age_of_domain': 1, 'DNSRecord': -1, 'web_traffic': 1, 'Page_Rank': 1, 'Google_Index': 1, 'Links_pointing_to_page': 0, 'Statistical_rep

In [46]:
import pandas as pd

data = pd.DataFrame({
    'Name': ['A', 'B'],
    'Age': [20, 25]
})

print(data)

  Name  Age
0    A   20
1    B   25

In [49]:
data.T

       0   1
Name   A   B
Age   20  25

In [48]:
data.T.to_json()

'{"0":{"Name":"A","Age":20},"1":{"Name":"B","Age":25}}'

In [52]:
list(json.loads(data.T.to_json()).values())

[{'Name': 'A', 'Age': 20}, {'Name': 'B', 'Age': 25}]